version: "2.4"

networks:
  db-net:
    external:
      name: image-db-net

services:
  cpp-master:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cpp-master
    restart: always
    environment:
      - DEBUG=1
    volumes:
      - ./:/data # mount the master script from the fs of the dev node
      - ../kube_config/:/home/user/.kube # mount the kube credentials from the fs of the dev node
      - /share/data/cellprofiler/automation/:/cpp_work # mount the work and result nfs share from the fs of the dev node
    networks:
      - db-net
    command: ["python3", "/data/cpp_master.py"]
