apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpp-master
  namespace: cpp
  labels:
    app: cpp-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cpp-master
  template:
    metadata:
      labels:
        app: cpp-master
    spec:
#      initContainers:
#      - name: volume-permissions
#        image: busybox
#        command: ["/bin/sh"]
#        args: ["-c", "chmod 600 /root/.ssh/id_rsa"]
#        volumeMounts:
#        - name: uppmax-ssh
#          mountPath: /root/.ssh/
      containers:
      - name: cpp-master
        image: ghcr.io/pharmbio/cpp_master:stable
        imagePullPolicy: Always
        command: ["python3", "/cpp/cpp_master.py"]
        resources:
          limits:
            cpu: 6000m
            memory: 240Gi 
          requests:
            cpu: 1000m
            memory: 2Gi 
        volumeMounts:
        - mountPath: /root/.kube/
          name: kube-config
        - mountPath: /cpp_work
          name: cpp2
        - mountPath: /root/.ssh/id_rsa
          subPath: id_rsa
          name: uppmax-ssh  
      restartPolicy: Always
      nodeSelector:
        kubernetes.io/hostname: brolin
      priorityClassName: normal-priority-preempt
      volumes:
     # - name: cpp
     #   persistentVolumeClaim:
     #     claimName: cpp-pvc
      - name: cpp2
        persistentVolumeClaim:
          claimName: cpp2-pvc
      - name: kube-config
        secret:
          secretName: cpp-user-kube-config
      - name: uppmax-ssh
        secret:
          secretName: uppmax-ssh
          defaultMode: 384
