apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpp-master
  namespace: cpp
  labels:
    app: cpp-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cpp-master
  template:
    metadata:
      labels:
        app: cpp-master
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - brolin
      containers:
      - name: cpp-master
        image: ghcr.io/pharmbio/cpp_master:stable
        imagePullPolicy: Always
        command: ["python3", "/cpp/cpp_master.py"]
        resources:
          limits:
            cpu: 8000m
            memory: 96Gi 
          requests:
            cpu: 1000m
            memory: 2Gi 
        volumeMounts:
        - mountPath: /root/.kube/
          name: kube-config
        - mountPath: /cpp_work
          name: cpp2
        #- mountPath: /cpp2_work
        #  name: cpp2
      restartPolicy: Always
      volumes:
     # - name: cpp
     #   persistentVolumeClaim:
     #     claimName: cpp-pvc
      - name: cpp2
        persistentVolumeClaim:
          claimName: cpp2-pvc
      - name: kube-config
        secret:
          secretName: cpp-user-kube-config
